cmake,build: move boost chrono to all components
Recently, gr-iio builds have started to fail on OS X with:
```
Undefined symbols for architecture x86_64:
  "boost::chrono::steady_clock::now()", referenced from:
      void boost::this_thread::sleep_for<long long, boost::ratio<1l, 1000l> >(boost::chrono::duration<long long, boost::ratio<1l, 1000l> > const&) in attr_source_impl.cc.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

This change moves the chrono boost component to be required by all archs.
At the moment Linux does not fail, but maybe later we might need to do it
as well.

Signed-off-by: Alexandru Ardelean <alexandru.ardelean@analog.com>