CMakeLists.txt: Set C++ 11 standard
This fixes:
[ 28%] Building CXX object lib/CMakeFiles/gnuradio-iio.dir/iio_modulo_ff_impl.cc.o
In file included from /usr/include/c++/5/mutex:35:0,
                 from /home/michael/devel/git/gr-iio/lib/attr_updater_impl.h:26,
                 from /home/michael/devel/git/gr-iio/lib/attr_updater_impl.cc:26:
/usr/include/c++/5/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support \
  ^
In file included from /home/michael/devel/git/gr-iio/lib/attr_updater_impl.cc:26:0:
/home/michael/devel/git/gr-iio/lib/attr_updater_impl.h:42:12: error: ‘mutex’ in namespace ‘std’ does not name a type
       std::mutex d_mtx;
            ^
/home/michael/devel/git/gr-iio/lib/attr_updater_impl.cc: In member function ‘virtual void gr::iio::attr_updater_impl::set_value(std::__cxx11::string)’:
/home/michael/devel/git/gr-iio/lib/attr_updater_impl.cc:83:9: error: ‘d_mtx’ was not declared in this scope
         d_mtx.lock();
         ^
/home/michael/devel/git/gr-iio/lib/attr_updater_impl.cc: In member function ‘virtual bool gr::iio::attr_updater_impl::start()’:
/home/michael/devel/git/gr-iio/lib/attr_updater_impl.cc:96:11: error: ‘d_mtx’ was not declared in this scope
           d_mtx.lock();
           ^
/home/michael/devel/git/gr-iio/lib/attr_updater_impl.cc: In member function ‘void gr::iio::attr_updater_impl::run()’:
/home/michael/devel/git/gr-iio/lib/attr_updater_impl.cc:124:13: error: ‘d_mtx’ was not declared in this scope
             d_mtx.lock();

Signed-off-by: Michael Hennerich <michael.hennerich@analog.com>